# Generated by Django 2.2 on 2020-05-16 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_auto_20200516_2113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='visit_details',
            new_name='visit_detail',
        ),
    ]
