version: '3.7'

services:
    web:
        build: .
        command: gunicorn code/ayurtantra_project/wsgi:application -b 0.0.0.0:8000
        volumes:
            - .:/code
        ports:
            - 8000:8000